# application.properties

# server.port = 18090
server:
    port: 18090
# spring.application.name=msa-gateway
spring:
    application:
        name: msa-gateway

# eureka.client.serviceUrl.defaultZone=http://localhost:18761/eureka/
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:18761/eureka/

# zuul.routes.msa-user-service.path=/api/user/**
# zuul.sensitiveHeaders= Cookie,Set-Cookie
zuul:
    sensitive-headers: Cookie,Set-Cookie
    routes:
        msa-user-service:
            path: /api/user/**
        msa-log-service:
            path: /api/log/**
            
jwt:
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
