# application.properties

# server.port = 18090
server:
    port: 18090
# spring.application.name=server-gateway
spring:
    application:
        name: server-gateway

# eureka.client.serviceUrl.defaultZone=http://localhost:18761/eureka/
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:18761/eureka/

# zuul.routes.app-api-user.path=/api/user/**
# zuul.sensitiveHeaders= Cookie,Set-Cookie
zuul:
    sensitive-headers: Cookie,Set-Cookie
    routes:
        app-api-user:
            path: /api/user/**
        app-api-log:
            path: /api/log/**
            
jwt:
  base64-secret: c2VjcmV0MTJzZWNyZXQxMnNlY3JldDEyc2VjcmV0MTI=
