server:
    port: 18090
spring:
    application:
        name: cyh-msa-server-gateway

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:18761/eureka/

zuul:
    sensitive-headers: Cookie,Set-Cookie
    routes:
        cyh-msa-app-api-user:
            path: /api/user/**
        cyh-msa-app-api-log:
            path: /api/log/**
            
jwt:
  base64-secret: c2VjcmV0MTJzZWNyZXQxMnNlY3JldDEyc2VjcmV0MTI=
