server: 
    port: 18000

spring:
    application: 
        name: msa-user-service #eureka 에 등록 됨 #gateway 설정에 route 추가
    profiles: 
        active: local
    jpa: 
        database: mysql
        show-sql: false # API 호출시, SQL 문을 콘솔에 출력한다.
        generate-ddl: false # DDL 정의시 데이터베이스의 고유 기능을 사용합니다. ex) 테이블 생성, 삭제 등
        hibernate: 
            ddl-auto: validate
        properties: 
            hibernate: 
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    datasource: # MySQL 설정
        url: jdbc:mysql://localhost:13306/msa_example?serverTimezone=Asia/Seoul
        username: user
        password: user123
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialization-mode: never
    rabbitmq: #RabbitMQ connection 설정
        host: localhost
        port: 5672
        username: guest
        password: guest
    cloud:
        stream:
            rabbit: #메시지 바인딩
                bindings:
                    user-update:
                        producer: #발행 설정
                            exchangeType: fanout
                            exchangeAutoDelete: true
eureka:
    client: 
        serviceUrl: 
            defaultZone: http://localhost:18761/eureka/
jwt:
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=

--- # dev 설정
spring:
    profiles: dev
    datasource: # MySQL 설정
        url: jdbc:mysql://localhost:13306/CCTV_SERVICE?serverTimezone=Asia/Seoul
eureka:
    client: 
        serviceUrl: 
            defaultZone: http://localhost:18761/eureka/
